import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Auth0ProviderWrapper from '@/components/Auth/Auth0Provider';
import { StoreWrapper } from '@/store/storeProvider';

import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Device management dashboard',
  description: 'Generated by Duc Huynh - Fullstack developer',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Auth0ProviderWrapper>
        <StoreWrapper>
          <AntdRegistry>
            <body className={inter.className}>{children}</body>
          </AntdRegistry>
        </StoreWrapper>
      </Auth0ProviderWrapper>
    </html>
  );
}
